# DB ??
spring.datasource.url=jdbc:mariadb://39.118.89.191:3306/community?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul
spring.datasource.username=myh0518
spring.datasource.password=moonin0610!!
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# JWT ??
jwt.secret=communitySecretKey1234567890communitySecretKey1234567890
jwt.expiration=86400000

# ?? ??
server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=moonyh518@gmail.com
spring.mail.password=etes haud hpzg ybdr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true